version: '2'
services:
  mongo:
    image: mongo:3.4.6
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
        - 27017:27017
    command: mongod --smallfiles
  back:
    links:
      - mongo
    depends_on:
      - mongo
    container_name: "backend"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080